version: '3.7'

services:
  cc-frontend:
    container_name: cc-frontend
    build:
      context: ./cc-frontend
      dockerfile: Dockerfile
    ports:
      - 3000
    networks:
      - cult-creative

  cc-backend:
    container_name: cc-backend
    build:
      context: ./cc-backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./cc-backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - baseURL=yourdomain.com
    volumes:
      - ./cc-backend:/app
      - /app/node_modules
    ports:
      - 3001
    networks:
      - cult-creative

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - cult-creative
    depends_on:
      - cc-frontend
      - cc-backend

networks:
  cult-creative:
    driver: bridge